/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as OwnerInventoryRouteImport } from './routes/owner.inventory'
import { Route as OwnerHistoryRouteImport } from './routes/owner.history'
import { Route as OwnerCasesRouteImport } from './routes/owner.cases'
import { Route as OwnerCalendarRouteImport } from './routes/owner.calendar'
import { Route as OwnerAnalyticsRouteImport } from './routes/owner.analytics'
import { Route as OwnerCasesIndexRouteImport } from './routes/owner.cases.index'
import { Route as OwnerCasesCaseIdRouteImport } from './routes/owner.cases.$caseId'
import { Route as OwnerCasesCaseIdIndexRouteImport } from './routes/owner.cases.$caseId.index'
import { Route as OwnerCasesCaseIdChatRouteImport } from './routes/owner.cases.$caseId.chat'

const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerInventoryRoute = OwnerInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerHistoryRoute = OwnerHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerCasesRoute = OwnerCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerCalendarRoute = OwnerCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerAnalyticsRoute = OwnerAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => OwnerRoute,
} as any)
const OwnerCasesIndexRoute = OwnerCasesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerCasesRoute,
} as any)
const OwnerCasesCaseIdRoute = OwnerCasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => OwnerCasesRoute,
} as any)
const OwnerCasesCaseIdIndexRoute = OwnerCasesCaseIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OwnerCasesCaseIdRoute,
} as any)
const OwnerCasesCaseIdChatRoute = OwnerCasesCaseIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => OwnerCasesCaseIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRouteWithChildren
  '/owner/analytics': typeof OwnerAnalyticsRoute
  '/owner/calendar': typeof OwnerCalendarRoute
  '/owner/cases': typeof OwnerCasesRouteWithChildren
  '/owner/history': typeof OwnerHistoryRoute
  '/owner/inventory': typeof OwnerInventoryRoute
  '/owner/': typeof OwnerIndexRoute
  '/owner/cases/$caseId': typeof OwnerCasesCaseIdRouteWithChildren
  '/owner/cases/': typeof OwnerCasesIndexRoute
  '/owner/cases/$caseId/chat': typeof OwnerCasesCaseIdChatRoute
  '/owner/cases/$caseId/': typeof OwnerCasesCaseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/owner/analytics': typeof OwnerAnalyticsRoute
  '/owner/calendar': typeof OwnerCalendarRoute
  '/owner/history': typeof OwnerHistoryRoute
  '/owner/inventory': typeof OwnerInventoryRoute
  '/owner': typeof OwnerIndexRoute
  '/owner/cases': typeof OwnerCasesIndexRoute
  '/owner/cases/$caseId/chat': typeof OwnerCasesCaseIdChatRoute
  '/owner/cases/$caseId': typeof OwnerCasesCaseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/owner': typeof OwnerRouteWithChildren
  '/owner/analytics': typeof OwnerAnalyticsRoute
  '/owner/calendar': typeof OwnerCalendarRoute
  '/owner/cases': typeof OwnerCasesRouteWithChildren
  '/owner/history': typeof OwnerHistoryRoute
  '/owner/inventory': typeof OwnerInventoryRoute
  '/owner/': typeof OwnerIndexRoute
  '/owner/cases/$caseId': typeof OwnerCasesCaseIdRouteWithChildren
  '/owner/cases/': typeof OwnerCasesIndexRoute
  '/owner/cases/$caseId/chat': typeof OwnerCasesCaseIdChatRoute
  '/owner/cases/$caseId/': typeof OwnerCasesCaseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/owner'
    | '/owner/analytics'
    | '/owner/calendar'
    | '/owner/cases'
    | '/owner/history'
    | '/owner/inventory'
    | '/owner/'
    | '/owner/cases/$caseId'
    | '/owner/cases/'
    | '/owner/cases/$caseId/chat'
    | '/owner/cases/$caseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/owner/analytics'
    | '/owner/calendar'
    | '/owner/history'
    | '/owner/inventory'
    | '/owner'
    | '/owner/cases'
    | '/owner/cases/$caseId/chat'
    | '/owner/cases/$caseId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/owner'
    | '/owner/analytics'
    | '/owner/calendar'
    | '/owner/cases'
    | '/owner/history'
    | '/owner/inventory'
    | '/owner/'
    | '/owner/cases/$caseId'
    | '/owner/cases/'
    | '/owner/cases/$caseId/chat'
    | '/owner/cases/$caseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OwnerRoute: typeof OwnerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/inventory': {
      id: '/owner/inventory'
      path: '/inventory'
      fullPath: '/owner/inventory'
      preLoaderRoute: typeof OwnerInventoryRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/history': {
      id: '/owner/history'
      path: '/history'
      fullPath: '/owner/history'
      preLoaderRoute: typeof OwnerHistoryRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/cases': {
      id: '/owner/cases'
      path: '/cases'
      fullPath: '/owner/cases'
      preLoaderRoute: typeof OwnerCasesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/calendar': {
      id: '/owner/calendar'
      path: '/calendar'
      fullPath: '/owner/calendar'
      preLoaderRoute: typeof OwnerCalendarRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/analytics': {
      id: '/owner/analytics'
      path: '/analytics'
      fullPath: '/owner/analytics'
      preLoaderRoute: typeof OwnerAnalyticsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/owner/cases/': {
      id: '/owner/cases/'
      path: '/'
      fullPath: '/owner/cases/'
      preLoaderRoute: typeof OwnerCasesIndexRouteImport
      parentRoute: typeof OwnerCasesRoute
    }
    '/owner/cases/$caseId': {
      id: '/owner/cases/$caseId'
      path: '/$caseId'
      fullPath: '/owner/cases/$caseId'
      preLoaderRoute: typeof OwnerCasesCaseIdRouteImport
      parentRoute: typeof OwnerCasesRoute
    }
    '/owner/cases/$caseId/': {
      id: '/owner/cases/$caseId/'
      path: '/'
      fullPath: '/owner/cases/$caseId/'
      preLoaderRoute: typeof OwnerCasesCaseIdIndexRouteImport
      parentRoute: typeof OwnerCasesCaseIdRoute
    }
    '/owner/cases/$caseId/chat': {
      id: '/owner/cases/$caseId/chat'
      path: '/chat'
      fullPath: '/owner/cases/$caseId/chat'
      preLoaderRoute: typeof OwnerCasesCaseIdChatRouteImport
      parentRoute: typeof OwnerCasesCaseIdRoute
    }
  }
}

interface OwnerCasesCaseIdRouteChildren {
  OwnerCasesCaseIdChatRoute: typeof OwnerCasesCaseIdChatRoute
  OwnerCasesCaseIdIndexRoute: typeof OwnerCasesCaseIdIndexRoute
}

const OwnerCasesCaseIdRouteChildren: OwnerCasesCaseIdRouteChildren = {
  OwnerCasesCaseIdChatRoute: OwnerCasesCaseIdChatRoute,
  OwnerCasesCaseIdIndexRoute: OwnerCasesCaseIdIndexRoute,
}

const OwnerCasesCaseIdRouteWithChildren =
  OwnerCasesCaseIdRoute._addFileChildren(OwnerCasesCaseIdRouteChildren)

interface OwnerCasesRouteChildren {
  OwnerCasesCaseIdRoute: typeof OwnerCasesCaseIdRouteWithChildren
  OwnerCasesIndexRoute: typeof OwnerCasesIndexRoute
}

const OwnerCasesRouteChildren: OwnerCasesRouteChildren = {
  OwnerCasesCaseIdRoute: OwnerCasesCaseIdRouteWithChildren,
  OwnerCasesIndexRoute: OwnerCasesIndexRoute,
}

const OwnerCasesRouteWithChildren = OwnerCasesRoute._addFileChildren(
  OwnerCasesRouteChildren,
)

interface OwnerRouteChildren {
  OwnerAnalyticsRoute: typeof OwnerAnalyticsRoute
  OwnerCalendarRoute: typeof OwnerCalendarRoute
  OwnerCasesRoute: typeof OwnerCasesRouteWithChildren
  OwnerHistoryRoute: typeof OwnerHistoryRoute
  OwnerInventoryRoute: typeof OwnerInventoryRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerAnalyticsRoute: OwnerAnalyticsRoute,
  OwnerCalendarRoute: OwnerCalendarRoute,
  OwnerCasesRoute: OwnerCasesRouteWithChildren,
  OwnerHistoryRoute: OwnerHistoryRoute,
  OwnerInventoryRoute: OwnerInventoryRoute,
  OwnerIndexRoute: OwnerIndexRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OwnerRoute: OwnerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
